<?php
/**
 * Created by PhpStorm.
 * User: 65100
 * Date: 2018/11/6
 * Time: 19:52
 */

namespace app\common\controller;

use think\Controller;
use think\facade\Session;

class Base extends Controller
{
    /**
     * 初始化方法
     *  在所有方法之前调用
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    // 检测管理员是否登录
    public function isAdminLogined()
    {
        if (!Session::get('admin_id')) {
            $this->error('请先登录', 'admin/user/renderAdminLoginPage');
        }
    }

    // 检测用户是否登录
    public function isUserLogined()
    {
        if (!Session::get('user_id')) {
            $this->error('请先登录', 'index/user/login');
        }
    }
}