<?php
/**
 * Created by PhpStorm.
 * User: 65100
 * Date: 2018/11/26
 * Time: 3:15
 */

namespace app\index\common\controller;

use think\Controller;
use think\facade\Session;
use think\Db;
use think\facade\Request;

class Base extends Controller
{
    /**
     * 初始化方法
     *  在所有方法之前调用
     */
    protected function initialize()
    {
        $this->is_open();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    // 检测用户是否登录
    public function isUserLogined()
    {
        if (!Session::get('user_id')) {
            $this->error('请先登录', 'index/user/login');
        }
    }

    // 检测网站是否关闭
    protected function is_open()
    {
        $is_open = Db::table('platform_site')->where('id', '=', '1')->value('is_open');
        if (0 == $is_open && 'index' == Request::module()) {
            $info = <<< 'info'
            <body class="bg-danger">
            <h1 class="text-danger" style="text-align: center; margin: 200px;">站点维护中...</h1>
</body>
info;
            exit($info);
        }
    }

    // 检测网站注册是否关闭
    protected function is_reg()
    {
        $is_reg = Db::table('platform_site')->where('id', '=', '1')->value('is_reg');
        if (0 == $is_reg) {
            $this->error('本网站暂不提供注册功能,请谅解', 'index/index');
        }
    }

    // 检测网站是否允许用户登录
    protected function is_login()
    {
        $is_login = Db::table('platform_site')->where('id', '=', '1')->value('is_login');
        if (0 == $is_login) {
            $this->error('本网站暂不提供用户登录功能,请谅解', 'index/index');
        }
    }

    // 检测网站是否允许用户评论
    protected function is_comment()
    {
        $is_comment = Db::table('platform_site')->where('id', '=', '1')->value('is_comment');
        if (0 == $is_comment) {
            $this->error('本网站暂不提供用户评论功能,请谅解', 'index/index');
        }
    }

    // 检测网站是否允许用户交易
    protected function is_deal()
    {
        $is_deal = Db::table('platform_site')->where('id', '=', '1')->value('is_deal');
        if (0 == $is_deal) {
            $this->error('本网站暂不提供用户交易功能,请谅解', 'index/index');
        }
    }

    // 黑名单用户不能登录
    public function is_black_user($id)
    {
        $status = Db::table('platform_user')->where([
            ['id', '=', $id]
        ])->value('status');
        if (0 == $status) {
            $this->error('你已被加入黑用户名单，暂时不能使用网站部分功能，请谅解', 'index/index');
        }
    }
}